export const INIT_FETCH_DATA = 'INIT_FETCH_DATA';
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED';

export const INIT_FETCH_LIVE_DATA = 'INIT_FETCH_LIVE_DATA';
export const FETCH_LIVE_DATA_START = 'FETCH_LIVE_DATA_START';
export const FETCH_LIVE_DATA_SUCCESS = 'FETCH_LIVE_DATA_SUCCESS';
export const FETCH_LIVE_DATA_FAILED = 'FETCH_LIVE_DATA_FAILED';

export const INIT_FETCH_USECASE = 'INIT_FETCH_USECASE';
export const FETCH_USECASE_START = 'FETCH_USECASE_START';
export const FETCH_USECASE_SUCCESS = 'FETCH_USECASE_SUCCESS';
export const FETCH_USECASE_FAILED = 'FETCH_USECASE_FAILED';

export const INIT_FETCH_ARDUINO_DATA = 'INIT_FETCH_ARDUINO_DATA';
export const FETCH_ARDUINO_DATA_START = 'FETCH_ARDUINO_DATA_START';
export const FETCH_ARDUINO_DATA_SUCCESS = 'FETCH_ARDUINO_DATA_SUCCESS';
export const FETCH_ARDUINO_DATA_FAILED = 'FETCH_ARDUINO_DATA_FAILED';
