export const INIT_FETCH_HISTORIC_DATA = 'INIT_FETCH_DATA';
export const FETCH_HISTORIC_DATA_START = 'FETCH_HISTORIC_DATA_START';
export const FETCH_HISTORIC_DATA_SUCCESS = 'FETCH_HISTORIC_DATA_SUCCESS';
export const FETCH_HISTORIC_DATA_FAILED = 'FETCH_HISTORIC_DATA_FAILED';

export const INIT_FETCH_USECASE_DATA = 'INIT_FETCH_USECASE_DATA';
export const FETCH_USECASE_DATA_START = 'FETCH_USECASE_DATA_START';
export const FETCH_USECASE_DATA_SUCCESS = 'FETCH_USECASE_DATA_SUCCESS';
export const FETCH_USECASE_DATA_FAILED = 'FETCH_USECASE_DATA_FAILED';

export const INIT_FETCH_LIVE_DATA = 'INIT_FETCH_LIVE_DATA';
export const FETCH_LIVE_DATA_START = 'FETCH_LIVE_DATA_START';
export const FETCH_LIVE_DATA_SUCCESS = 'FETCH_LIVE_DATA_SUCCESS';
export const FETCH_LIVE_DATA_FAILED = 'FETCH_LIVE_DATA_FAILED';

export const INIT_FETCH_USECASE = 'INIT_FETCH_USECASE';
export const FETCH_USECASE_START = 'FETCH_USECASE_START';
export const FETCH_USECASE_SUCCESS = 'FETCH_USECASE_SUCCESS';
export const FETCH_USECASE_FAILED = 'FETCH_USECASE_FAILED';

export const INIT_UPDATE_USECASE = 'INIT_UPDATE_USECASE';
export const UPDATE_USECASE_START = 'UPDATE_USECASE_START';
export const UPDATE_USECASE_SUCCESS = 'UPDATE_USECASE_SUCCESS';
export const UPDATE_USECASE_FAILED = 'UPDATE_USECASE_FAILED';

export const INIT_FETCH_ARDUINO_DATA = 'INIT_FETCH_ARDUINO_DATA';
export const FETCH_ARDUINO_DATA_START = 'FETCH_ARDUINO_DATA_START';
export const FETCH_ARDUINO_DATA_SUCCESS = 'FETCH_ARDUINO_DATA_SUCCESS';
export const FETCH_ARDUINO_DATA_FAILED = 'FETCH_ARDUINO_DATA_FAILED';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_ROLE = 'AUTH ROLE';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const INIT_FETCH_USERS_DATA = 'INIT_FETCH_USERS_DATA';
export const FETCH_USERS_DATA_START = 'FETCH_USERS_DATA_START';
export const FETCH_USERS_DATA_SUCCESS = 'FETCH_USERS_DATA_SUCCESS';
export const FETCH_USERS_DATA_FAILED = 'FETCH_USERS_DATA_FAILED';
